name: Docker Build and Deploy

on:
  # Workflow Manual
  workflow_dispatch:
    inputs:
      isRequiredRemoteDeploy:
        type: boolean
        description: 원격 서버 배포

  # Workflow Event
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

env:
  CACHED_BUILD_PATHS: ${{ github.workspace }}/build
  BUILD_CACHE_KEY: ${{ github.sha }}
  REGISTRY_URL: registry.gitlab.com/codingflowerdog/dev
  REGISTRY_NAME: spring-boot-example

jobs:
  # Deploy
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Remote Deploy
      - name: Remote Deploy
        if: ${{ github.event.inputs.isRequiredRemoteDeploy }} == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            bash --login
            docker pull ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_NAME }}:${{ github.run_number }}
            docker run -it -d -p ${{ secrets.DOCKER_PORT }}:${{ secrets.APPLICATION_PORT }} --name ${{ env.REGISTRY_NAME }} ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_NAME }}:${{ github.run_number }}
