name: Docker Build and Deploy

on:
  # Workflow Manual
  workflow_dispatch:
    inputs:
      boolean:
        type: boolean
        description: 원격 서버 배포 (TODO)

  # Workflow Event
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

env:
  CACHED_BUILD_PATHS: ${{ github.workspace }}/build
  BUILD_CACHE_KEY: ${{ github.sha }}
  REPOSITORY_NAME: spring-boot-example
  REGISTRY_URL: registry.gitlab.com/codingflowerdog/dev
  REGISTRY_NAME: spring-boot-example

jobs:
  # Deploy
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Remote Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            whoami
            ls
