name: Docker Build and Deploy

on:
  # Workflow Manual
  workflow_dispatch:
    inputs:
      isRequiredRemoteDeploy:
        type: boolean
        description: 원격 서버 배포

  # Workflow Event
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

env:
  CACHED_BUILD_PATHS: ${{ github.workspace }}/build
  BUILD_CACHE_KEY: ${{ github.sha }}
  REGISTRY_URL: registry.gitlab.com/codingflowerdog/dev
  REGISTRY_NAME: spring-boot-example

jobs:
  # Gradle Build
  gradle-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # JAVA 설정
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      # Gradle build
      - name: Build with Gradle
        id: gradle-build
        run: |
          chmod +x gradlew
          ./gradlew build

      # 빌드 결과 업로드
      - name: Upload Build File
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/libs/app.jar
  
  # Docker Build
  docker-build:
    runs-on: ubuntu-latest
    needs: gradle-build
    
    steps:
      - uses: actions/checkout@v2
      
      # 빌드 결과 다운로드
      - name: Download Build File
        uses: actions/download-artifact@v2
        with:
          name: build

      # 빌드 파일 경로 설정
      - name: Create Build Directory
        run: |
          mkdir -p build/libs 
          mv app.jar build/libs/app.jar

      # Docker 빌드
      - name: Docker Build
        run: |
          docker build -t spring-boot-example .
          docker tag spring-boot-example:latest ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_NAME }}:${{ github.run_number }}

      # Upload Docker Image Artifact
      - name: Upload Docker Image Artifact
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_NAME }}:${{ github.run_number }}

  # Deploy
  deploy:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      # Download Docker Image Artifact
      - name: Download Docker Image Artifact
        uses: ishworkh/docker-image-artifact-download@v1
        with:
          image: ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_NAME }}:${{ github.run_number }}

      # Gitlab 로그인
      - name: Gitlab Login
        run: docker login https://registry.gitlab.com/my_registry -u ${{ secrets.GITLAB_USER_NAME }} -p ${{ secrets.GITLAB_CONTAINER_ACCESS_TOKEN }}

      # Docker Push
      - name: Gitlab Push
        run: docker push ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_NAME }}:${{ github.run_number }}
      
      # Remote Deploy
      - name: Remote Deploy
        if: ${{ github.event.inputs.isRequiredRemoteDeploy }} == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            docker pull ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_NAME }}:${{ github.run_number }}
            docker run -it -d -p ${{ secrets.DOCKER_PORT }}:${{ secrets.APPLICATION_PORT }} --name ${{ env.REGISTRY_NAME }} ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_NAME }}:${{ github.run_number }}
